### ISSUE TITLE
Feature request: kunna lägga till en kort text efter emojin

### ISSUE THREAD

**Issue by maxim0x2929** [AlexGustafsson/irc-emoji-bot#1]
Feature request: kunna lägga till en kort text efter emojin kanske :p

┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿ freeze, sucka!!!

**Comment by AlexGustafsson** [comment]
Implemented in [v0.2](https://github.com/AlexGustafsson/irc-emoji-bot/commit/f67d7aac8adc87c30986d9fc6a63c8e45710984d). Closing.
